In [1]:
from vectorizer import get_available_methods, preprocess, preprocess_tokenize, vectorize
import pandas as pd
import numpy as np
import os
import re

In [2]:
get_available_methods()

Available vectorization methods:

['tf-idf', 'tf-idf-svd', 'word2vec', 'word2vec-tfidf', 'bert', 'finbert']

In [3]:
df = pd.read_parquet('../data/data_sample/news_prices_full_processed_with_target.parquet')
df

,date,prev_date,future_date,title,description,maintext,ticker,prev_day_price,curr_day_price,next_day_price,...,language,curr_prev_per_change,next_curr_per_change,curr_prev_pos_change,next_curr_pos_change,title_word_count,description_word_count,maintext_word_count,title + description + maintext,title + description
0,2019-01-22,2019-01-21,2019-01-23,UBS Warns on Client Activity After $13 Billion...,Withdrawals at the Zurich-based bank’s key glo...,(Bloomberg) -- UBS Group AG warned client acti...,C,63.12000,61.85000,62.13000,...,en,-0.020120,0.004527,0,1,10,46,707,UBS Warns on Client Activity After $13 Billion...,UBS Warns on Client Activity After $13 Billion...
1,2019-08-01,2019-07-31,2019-08-02,Shopify Boosts Outlook on New Online Offerings,(Bloomberg) -- Shopify Inc. shares continued t...,(Bloomberg) -- Shopify Inc. shares continued t...,SHOP,317.88000,341.39001,332.19000,...,en,0.073959,-0.026949,1,0,7,42,459,Shopify Boosts Outlook on New Online Offerings...,Shopify Boosts Outlook on New Online Offerings...
2,2019-10-31,2019-10-30,2019-11-01,Wayfair Plunges as Forecast Miss Heightens Gro...,(Bloomberg) -- Wayfair Inc. plunged near its l...,(Bloomberg) -- Wayfair Inc. plunged near its l...,C,72.97000,71.86000,73.84000,...,en,-0.015212,0.027554,0,1,8,51,315,Wayfair Plunges as Forecast Miss Heightens Gro...,Wayfair Plunges as Forecast Miss Heightens Gro...
3,2019-02-08,2019-02-07,2019-02-09,Skyscrapers Made of Wood Are Making a Comeback,"Sidewalk Labs LLC, a unit of Google parent Alp...",(Bloomberg) -- More than a century after steel...,GOOGL,1098.70996,1095.06006,1095.01001,...,en,-0.003322,-0.000046,0,0,8,48,657,Skyscrapers Made of Wood Are Making a Comeback...,Skyscrapers Made of Wood Are Making a Comeback...
4,2019-01-24,2019-01-23,2019-01-25,Intel Sales Miss as Data-Center Demand Slows; ...,Revenue in the current period will be about $1...,(Bloomberg) -- Intel Corp. reported lower-than...,GOOGL,1075.56995,1073.90002,1090.98999,...,en,-0.001553,0.015914,0,1,9,54,675,Intel Sales Miss as Data-Center Demand Slows; ...,Intel Sales Miss as Data-Center Demand Slows; ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87990,2021-02-17,2021-02-16,2021-02-18,'No Man's Sky' update lets players adopt alien...,You can ride giant creatures and companions ca...,Benzinga\nWarren Buffett's Berkshire Cuts Appl...,AAPL,133.19000,130.84000,129.71001,...,en,-0.017644,-0.008636,0,0,10,13,2821,'No Man's Sky' update lets players adopt alien...,'No Man's Sky' update lets players adopt alien...
87991,2021-02-17,2021-02-16,2021-02-18,'No Man's Sky' update lets players adopt alien...,You can ride giant creatures and companions ca...,Benzinga\nWarren Buffett's Berkshire Cuts Appl...,CVX,93.13000,95.92000,95.00000,...,en,0.029958,-0.009591,1,0,10,13,2821,'No Man's Sky' update lets players adopt alien...,'No Man's Sky' update lets players adopt alien...
87992,2021-02-17,2021-02-16,2021-02-18,'No Man's Sky' update lets players adopt alien...,You can ride giant creatures and companions ca...,Benzinga\nWarren Buffett's Berkshire Cuts Appl...,MRK,74.25000,75.54000,75.41000,...,en,0.017374,-0.001721,1,0,10,13,2821,'No Man's Sky' update lets players adopt alien...,'No Man's Sky' update lets players adopt alien...
87993,2021-02-17,2021-02-16,2021-02-18,'No Man's Sky' update lets players adopt alien...,You can ride giant creatures and companions ca...,Benzinga\nWarren Buffett's Berkshire Cuts Appl...,BRK,245.28000,370500.00000,245.25000,...,en,1509.518591,-0.999338,1,0,10,13,2821,'No Man's Sky' update lets players adopt alien...,'No Man's Sky' update lets players adopt alien...
87994,2021-10-14,2021-10-13,2021-10-15,Northern Star Resources Ltd. Ownership in Supe...,"TORONTO, Oct. 13, 2021 (GLOBE NEWSWIRE) -- Nor...","TORONTO, Oct. 13, 2021 (GLOBE NEWSWIRE) -- Nor...",T,25.30000,25.62000,25.70000,...,en,0.012648,0.003123,1,1,9,83,358,Northern Star Resources Ltd. Ownership in Supe...,Northern Star Resources Ltd. Ownership in Supe...

In [4]:
df = df[['maintext', 'next_curr_per_change']].dropna()
df

                                                maintext  next_curr_per_change
0      (Bloomberg) -- UBS Group AG warned client acti...              0.004527
1      (Bloomberg) -- Shopify Inc. shares continued t...             -0.026949
2      (Bloomberg) -- Wayfair Inc. plunged near its l...              0.027554
3      (Bloomberg) -- More than a century after steel...             -0.000046
4      (Bloomberg) -- Intel Corp. reported lower-than...              0.015914
...                                                  ...                   ...
87990  Benzinga\nWarren Buffett's Berkshire Cuts Appl...             -0.008636
87991  Benzinga\nWarren Buffett's Berkshire Cuts Appl...             -0.009591
87992  Benzinga\nWarren Buffett's Berkshire Cuts Appl...             -0.001721
87993  Benzinga\nWarren Buffett's Berkshire Cuts Appl...             -0.999338
87994  TORONTO, Oct. 13, 2021 (GLOBE NEWSWIRE) -- Nor...              0.003123

[87995 rows x 2 columns]

In [5]:
preprocessed, tokenized = preprocess_tokenize(df['maintext'].tolist())

Preprocessing and tokenizing corpus
Preprocessed 87995 documents

In [6]:
X_tfidf_svd, tf_idf_svd_pipeline = vectorize('tf-idf-svd', preprocessed, tokenized)

Vectorizing using method: tf-idf-svd
Creating TF-IDF matrix with SVD

In [7]:
X_tfidf_svd

array([[ 0.53378926, -0.0847338 ,  0.05707064, ...,  0.00928628,
         0.00548376,  0.0260748 ],
       [ 0.46891882, -0.0701804 ,  0.04459837, ..., -0.01233055,
         0.01369505, -0.0237744 ],
       [ 0.44354896, -0.12137594,  0.08981085, ..., -0.00510165,
        -0.00515347, -0.00982845],
       ...,
       [ 0.72796108, -0.1584297 ,  0.09868687, ...,  0.01084263,
        -0.00931093,  0.00848986],
       [ 0.72796108, -0.1584297 ,  0.09868687, ...,  0.01084263,
        -0.00931093,  0.00848986],
       [ 0.25673135,  0.05992851,  0.02416422, ..., -0.0077116 ,
        -0.01363545,  0.0103294 ]])

### CatBoost Regressor

In [8]:
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
X_train, X_test, y_train, y_test = train_test_split(X_tfidf_svd, df['next_curr_per_change'], test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)
print(f"Training set: {X_train.shape}, Validation set: {X_val.shape}, Test set: {X_test.shape}")

Training set: (52797, 300), Validation set: (17599, 300), Test set: (17599, 300)

In [9]:
model = CatBoostRegressor(iterations=1000, learning_rate=0.1, depth=6, random_state=42, verbose=100)
model.fit(X_train, y_train, eval_set=(X_val, y_val), early_stopping_rounds=50)

0:	learn: 0.1099135	test: 0.1067750	best: 0.1067750 (0)	total: 90.6ms	remaining: 1m 30s
100:	learn: 0.0871394	test: 0.0920924	best: 0.0920216 (81)	total: 1.65s	remaining: 14.7s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.09202161766
bestIteration = 81

Shrink model to first 82 iterations.

In [10]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")
print(f"Mean Absolute Error: {mae}")

Mean Squared Error: 0.010162253314609638
R^2 Score: 0.2797655967519679
Mean Absolute Error: 0.03149373105137971

In [12]:
X_bert, bert_model = vectorize('bert', preprocessed, tokenized)

Vectorizing using method: bert
Love. Death. TRANSFORMERS
Using device: mps
Creating Sentence-BERT embeddings

Batches:   0%|          | 0/2750 [00:00<?, ?it/s]

In [13]:
def median_absolute_error(y_true, y_pred):
    return np.median(np.abs(y_true - y_pred))

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_bert, df['next_curr_per_change'], test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)
print(f"Training set: {X_train.shape}, Validation set: {X_val.shape}, Test set: {X_test.shape}")

Training set: (52797, 384), Validation set: (17599, 384), Test set: (17599, 384)

In [16]:
model = CatBoostRegressor(iterations=1000, learning_rate=0.1, depth=6, random_state=42, verbose=100)
model.fit(X_train, y_train, eval_set=(X_val, y_val), early_stopping_rounds=50)

0:	learn: 0.1092850	test: 0.1065506	best: 0.1065506 (0)	total: 86.2ms	remaining: 1m 26s
100:	learn: 0.0863799	test: 0.0926817	best: 0.0926172 (95)	total: 2.03s	remaining: 18.1s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.09261716425
bestIteration = 95

Shrink model to first 96 iterations.

In [17]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
med_ae = median_absolute_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")
print(f"Mean Absolute Error: {mae}")
print(f"Median Absolute Error: {med_ae}")
print('Mean target value:', np.mean(df['next_curr_per_change']))

Mean Squared Error: 0.010298013215613883
R^2 Score: 0.27014381817022026
Mean Absolute Error: 0.030964693407477244
Median Absolute Error: 0.012789701372591559
Mean target value: -0.011500939035404245

In [ ]:
# TODO: delete outliers
df['next_curr_per_change'].describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

count    87995.000000
mean        -0.011501
std          0.112542
min         -0.999355
10%         -0.024881
20%         -0.013999
30%         -0.008155
40%         -0.003715
50%          0.000391
60%          0.003898
70%          0.008421
80%          0.013818
90%          0.022231
max          0.367639
Name: next_curr_per_change, dtype: float64

In [15]:
1 + 1

2

In [ ]:
# TODO: check all this
X_finbert, finbert_model = vectorize('finbert', preprocessed, tokenized)
X_word2vec, w2v_model = vectorize('word2vec', preprocessed, tokenized)